#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Stop and remove any existing container
  docker_container:
    name: iotpi
    state: absent

- name: Create pihole directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/iotpi

- name: Create and start container
  docker_container:
    name: iotpi
    hostname: iotpi
    image: "pihole/pihole:latest"
    pull: yes
    ip: 10.10.10.254
    capabilities:
      - NET_ADMIN
    published_ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8080:80"
      - "8443:443"
    env:
      USER_ID: "{{ uid }}"
      GROUP_ID: "{{ gid }}"
      TZ: "{{ tz }}"
      WEBPASSWORD: "{{ user.pass }}"
    labels:
      "com.github.homebox.homebox_managed": "true"
    volumes:
      - "/opt/iotpi/etc-pihole/:/etc/pihole/"
      - "/opt/iotpi/etc-dnsmasq.d/:/etc/dnsmasq.d/"
    networks:
      - name: IoT
        aliases:
          - iotpi
    purge_networks: yes
    restart_policy: always
    state: started
