#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: APT | Remove APT locks
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/var/lib/apt/lists/lock"
    - "/var/cache/apt/archives/lock"
    - "/var/lib/dpkg/lock"
