#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Stop and remove any existing container
  docker_container:
    name: influxdb
    state: absent

- name: Create influxdb directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/influxdb
    - /opt/scripts/influxdb

- name: Create and start container
  docker_container:
    name: influxdb
    hostname: influxdb
    image: "influxdb:latest"
    pull: yes
    published_ports:
      - "8086:8086"
    env:
      USER_ID: "{{ uid }}"
      GROUP_ID: "{{ gid }}"
    labels:
      "com.github.homebox.homebox_managed": "true"
    volumes:
      - "/opt/influxdb:/var/lib/influxdb:rw"
    networks:
      - name: redbeard
        aliases:
          - influxdb
    purge_networks: yes
    restart_policy: always
    state: started
