#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Stop and remove any existing container
  docker_container:
    name: grafana
    state: absent

- name: Create grafana directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/grafana
    - /opt/scripts/grafana

- name: Create and start container
  docker_container:
    name: grafana
    hostname: grafana
    image: "grafana/grafana"
    pull: yes
    published_ports:
      - "3000:3000"
    env:
      USER_ID: "{{ uid }}"
      GROUP_ID: "{{ gid }}"
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource"
    labels:
      "com.github.homebox.homebox_managed": "true"
    volumes:
      - "/opt/grafana:/config:rw"
      - "/etc/localtime:/etc/localtime:ro"      
    networks:
      - name: redbeard
        aliases:
          - grafana
    purge_networks: yes
    restart_policy: always
    state: started
