#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# Remove trailing forward slashes from backup paths
- name: Remove trailing forward slashes from backup paths
  set_fact:
    local_tmp: { destination: "{{ (local.destination | default('',true)) | regex_replace('\\/$', '') }}" }
    rclone_tmp: { destination: "{{ (rclone.destination | default('',true)) | regex_replace('\\/$', '') }}" }

- name: Merge changes back
  set_fact:
    local: "{{ local | combine(local_tmp) }}"
    rclone: "{{ rclone | combine(rclone_tmp) }}"
