#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Create common groups
  group: "name={{ item }} state=present"
  with_items:
    - docker
    - "{{ user.name }}"

- name: "Create user '{{ user.name }}'"
  user:
    name: "{{ user.name }}"
    group: "{{ user.name }}"
    groups: "{{ user.name }},sudo,video,docker"
    password: "{{ user.pass | string | password_hash('sha512') }}"
    update_password: on_create
    append: yes
  register: user_info

- name: Get vgid
  shell: "getent group video | cut -d: -f3"
  register: vgid_lookup

- name: "Set 'uid', 'gid', and 'vgid'"
  set_fact:
    uid: "{{ user_info.uid }}"
    gid: "{{ user_info.group }}"
    vgid: "{{ vgid_lookup.stdout }}"

- name: Check sudoers exists
  stat:
    path: "/etc/sudoers"
  register: etc_sudoers

- name: Set sudo group to NOPASSWD
  lineinfile:
    path: "/etc/sudoers"
    regexp: '^%sudo\s'
    line: '%sudo   ALL=(ALL) NOPASSWD:ALL'
    state: present
  when: etc_sudoers.stat.exists

- name: Create 'new_home_path' variable
  set_fact:
    new_home_path: "/home/{{ user.name }}"

- name: "Do following tasks when not in the user's homebox folder"
  block:

  - name: "Delete previous homebox folder if it exists"
    file:
      path: "/home/{{ user.name }}/homebox"
      state: absent

  - name: "Get current git branch"
    shell: git rev-parse --abbrev-ref HEAD
    register: git_branch

  - name: "Clone Homebox project"
    git:
      repo: "https://github.com/shaboigan/homebox.git"
      dest: "{{ new_home_path }}/homebox/"
      version: "{{ git_branch.stdout }}"
      clone: yes
      force: yes
    become: yes
    become_user: "{{ user.name }}"
    ignore_errors: yes

  - name: "Copy config files to homebox folder"
    copy:
      src: "{{ item }}"
      dest: "{{ new_home_path }}/homebox/"
      owner: "{{ user.name }}"
      group: "{{ user.name }}"
      decrypt: no
      force: yes
    with_fileglob:
      - "{{ playbook_dir }}/*.yml"
      - "{{ playbook_dir }}/*.cfg"
      - "{{ playbook_dir }}/*.conf"
      - "{{ playbook_dir }}/*.txt"
    ignore_errors: yes

  - name: "Look for '.ansible_vault' file in current home folder"
    stat:
      path: "{{ playbook_dir | dirname }}/.ansible_vault"
    register: ansible_vault

  - name: "Copy '.ansible_vault' to new home folder."
    copy:
      src: "{{ playbook_dir | dirname }}/.ansible_vault"
      dest: "{{ new_home_path }}"
      owner: "{{ user.name }}"
      group: "{{ user.name }}"
      mode: 0664
      force: yes
    when: (ansible_vault.stat.exists)

  - name: "Quit playbook after creation of new homebox folder location"
    fail:
      msg:
        - "Homebox folder was migrated to a home location."
        - "Please re-login with the '{{ user.name }}' account and rerun the {{
            ('restore' in ansible_run_tags) | ternary('restore tag','Homebox Installer') }}
            from the '{{ new_home_path }}/homebox/' path."
    when: ('preinstall' not in ansible_run_tags)

  - name: "Set preinstall variables"
    set_fact:
      preinstall_user_relogin: true
    when: ('preinstall' in ansible_run_tags)

  when: (playbook_dir != (new_home_path + '/homebox')) and not (continuous_integration)

- name: "Reset ownership of '{{ new_home_path }}/' path"
  file: "path={{ new_home_path }} state=directory owner={{ user.name }} group={{ user.name }} recurse=yes follow=no"
