#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
#    - name: "Set DNS Record on CloudFlare"
#  include_role:
#    name: cloudflare-dns
#  vars:
#    subdomain: displaycameras
#
#- name: Slurp hashed htpasswd
#  slurp:
#    src: "/opt/traefik/.htpasswd"
#  register: hashed
#
#- name: Set hashed password
#  set_fact:
#    htpasswd: "{{ hashed['content'] | b64decode }}"

- name: Stop and remove any existing container
  docker_container:
    name: displaycameras
    state: absent

- name: Create displaycameras directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/displaycameras
    - /opt/scripts/displaycameras

- name: Create and start container
  docker_container:
    name: displaycameras
    image: "hilschernetpi/netpi-desktop-hdmi"
    pull: yes
    published_ports:
      - 22:22
      - 5900:5900
    env:
      USER_ID: "{{ uid }}"
      GROUP_ID: "{{ gid }}"
      TZ: "{{ tz }}"
      SSHPORT: 22
    labels:
#      traefik.enable: "true"
#      traefik.backend: "displaycameras"
#      traefik.frontend.redirect.entryPoint: "https"
#      traefik.frontend.rule: "Host:displaycameras.{{ user.domain }}"
#      traefik.port: "5900"
#      traefik.frontend.auth.basic: "{{ htpasswd }}"
#      traefik.docker.network: "redbeard"
      "com.github.homebox.homebox_managed": "true"
    volumes:
      - "/opt/displaycameras:/config:rw"
    devices:
      - "/dev/tty0:/dev/tty0"
      - "/dev/tty2:/dev/tty2"
      - "/dev/fb0:/dev/fb0"
    networks:
      - name: redbeard
        aliases:
          - displaycameras
    purge_networks: yes
    restart_policy: always
    state: started
