#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Stop and remove any existing container
  docker_container:
    name: unbound
    state: absent

- name: Create Unbound directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/unbound
    - /opt/scripts/unbound

- name: Create and start container
  docker_container:
    name: unbound
    hostname: unbound
    image: "klutchell/unbound:arm64"
    pull: no
    network_mode: host
    published_ports:
      - "5053:5053/udp"
    env:
      USER_ID: "{{ uid }}"
      GROUP_ID: "{{ gid }}"
      WEBPASSWORD: "{{ user.pass }}"
      TZ: "{{ timezone }}"
    labels:
      "com.github.homebox.homebox_managed": "true"
    volumes:
      - "/opt/unbound:/opt/unbound"
#      - "/etc/localtime:/etc/localtime:ro"
#    networks:
#      - name: redbeard
#        aliases:
#          - unbound
    purge_networks: yes
    restart_policy: always
    state: started