#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Stop and remove any existing container
  docker_container:
    name: samba
    state: absent

- name: Create samba directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/samba
    - /opt/scripts/samba

- name: Create and start container
  docker_container:
    name: samba
    hostname: samba
    image: "dperson/samba:latest"
    pull: yes
    published_ports:
      - "139:139"
      - "445:445"
    env:
      USER1: "{{ uid }}"
      SHARE1: "share;/mount"
    labels:
      "com.github.homebox.homebox_managed": "true"
    volumes:
      - "/opt/samba:/config:rw"
      - "/mnt/ext-hdd:/mount"
      - "/etc/localtime:/etc/localtime:ro"      
    networks:
      - name: redbeard
        aliases:
          - samba
    purge_networks: yes
    restart_policy: always
    state: started
