#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# Import 'rclone.conf' from github

- name: "Import Config | Check if 'rclone.conf' exists at default location"
  stat:
    path: "/home/{{ user.name }}/.config/rclone/rclone.conf"
  register: rclone_conf

- name: "Import Config | Import rclone.conf from github"
  shell: "curl -Lo /home/{{ user.name }}/.config/rclone/rclone.conf '{{ rclone.config }}'"
  become: yes
  become_user: "{{ user.name }}"
  when: not rclone_conf.stat.exists

# Import 'rclone.conf' from playbook dir

- name: "Import Config | Check if 'rclone.conf' exists in '{{ playbook_dir }}'"
  stat:
    path: "{{ playbook_dir }}/rclone.conf"
  register: rclone_conf_playbook_dir

- name: "Import Config | Import 'rclone.conf' from '{{ playbook_dir }}'"
  block:

  - name: "Import Config | Check if a previous 'rclone.conf' exists"
    stat:
      path: "/home/{{ user.name }}/.config/rclone/rclone.conf"
    register: rclone_conf_default_path

  - name: "Import Config | Backup previous 'rclone.conf' (if it exists)"
    copy:
      src: "/home/{{ user.name }}/.config/rclone/rclone.conf"
      dest: "/home/{{ user.name }}/.config/rclone/rclone.conf.bak"
      owner: "{{ user.name }}"
      group: "{{ user.name }}"
      mode: 0775
      force: yes
    when: (rclone_conf_default_path.stat.exists)

  - name: "Import Config | Remove previous 'rclone.conf' (if it exists)"
    file:
      path: "/home/{{ user.name }}/.config/rclone/rclone.conf"
      state: absent
    when: (rclone_conf_default_path.stat.exists)

  - name: "Import Config | Import 'rclone.conf' from '{{ playbook_dir }}'"
    copy:
      src: "{{ playbook_dir }}/rclone.conf"
      dest: "/home/{{ user.name }}/.config/rclone/rclone.conf"
      owner: "{{ user.name }}"
      group: "{{ user.name }}"
      mode: 0775
      force: yes

  - name: "Import Config | Remove imported 'rclone.conf' from '{{ playbook_dir }}'"
    file:
      path: "{{ playbook_dir }}/rclone.conf"
      state: absent

  when: (rclone_conf_playbook_dir.stat.exists)

# Find and import 'rclone.conf' if located somewhere else

- name: "Import Config | Check if 'rclone.conf' exists at default location"
  stat:
    path: "/home/{{ user.name }}/.config/rclone/rclone.conf"
  register: rclone_conf_default_path_2

- name: "Import Config | Do the following block when 'rclone.conf' is not at default location"
  block:

  - name: "Import Config | Find location of 'rclone.conf' when not at default location"
    shell: rclone config file
    register: rclone_conf_current_location

  - name: "Import Config | Copy 'rclone.conf' to default location if found elsewhere"
    copy:
      src: "{{ rclone_conf_current_location.stdout_lines | last }}"
      dest: "/home/{{ user.name }}/.config/rclone/rclone.conf"
      owner: "{{ user.name }}"
      group: "{{ user.name }}"
      mode: 0775
      force: yes
    when: (rclone_conf_current_location.stdout.find('Configuration file doesn\'t exist') == -1)

  - name: "Import Config | Remove that other 'rclone.conf' copy"
    file:
      path: "{{ rclone_conf_current_location.stdout_lines | last }}"
      state: absent
    when: (rclone_conf_current_location.stdout.find('Configuration file doesn\'t exist') == -1)

  - name: "Import Config | Create blank 'rclone.conf' if not found elsewhere"
    file:
      path: "/home/{{ user.name }}/.config/rclone/rclone.conf"
      state: touch
      mode: 0775
      owner: "{{ user.name }}"
      group: "{{ user.name }}"
    when: (rclone_conf_current_location.stdout.find('Configuration file doesn\'t exist') != -1)

  when: not (rclone_conf_default_path_2.stat.exists)
