#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Docker | Daemon | Create override directory"
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: 0775

- name: "Docker | Daemon | Import override file"
  template:
    src: override.conf.j2
    dest: /etc/systemd/system/docker.service.d/override.conf
    mode: 0775
    force: no
  register: import

- name: "Docker | Daemon | Edit override file"
  ini_file:
    path: /etc/systemd/system/docker.service.d/override.conf
    section: Unit
    option: "After"
    value: "{{ 'unionfs' if (mounts.unionfs|lower) == 'unionfs' else 'mergerfs' }}.service"
    state: present
    no_extra_spaces: yes
  register: edit

- name: Docker | Daemon | Restart Docker Service
  block:

  - name: "Docker | Daemon | Systemd daemon-reload"
    systemd: name=docker state=reloaded daemon_reload=yes

  - name: "Docker | Daemon | Restart docker service"
    systemd: name=docker state=restarted

  - name: "Docker | Daemon | Wait for 30 seconds before commencing"
    wait_for:
      timeout: 30

  when: import.changed or edit.changed
