#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Get ansible-playbook binary path."
  shell: "which ansible-playbook"
  register: playbook_binary

- name: "Remove legacy cron backup task."
  cron:
    name: "Backup Homebox"
    state: absent

- name: "Schedule cron backup."
  cron:
    name: "Homebox Backup"
    special_time: "{{ cron.cron_time }}"
    job: "sudo PATH='/usr/bin:/bin:/usr/local/bin' env ANSIBLE_CONFIG='{{ playbook_dir }}/ansible.cfg' '{{ playbook_binary.stdout }}' '{{ playbook_dir }}/backup.yml' >> '/home/{{ user.name }}/logs/homebox_backup.log' 2>&1"
    state: "{{ cron.cron_state }}"
    user: "{{ user.name }}"
