#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# Remove trailing forward slashes from backup paths
- name: Remove trailing forward slashes from backup paths
  set_fact:
    local_tmp: { destination: "{{ (local.destination | default('',true)) | regex_replace('\\/$', '') }}" }
    rclone_tmp: { destination: "{{ (rclone.destination | default('',true)) | regex_replace('\\/$', '') }}" }

- name: Merge changes back
  set_fact:
    local: "{{ local | combine(local_tmp) }}"
    rclone: "{{ rclone | combine(rclone_tmp) }}"

# Restore service
- name: "Set 'restore_service_enabled' variable"
  set_fact:
    restore_service_enabled: "{{ true if not(
        (restore_service is undefined)
        or
        (restore_service is none)
        or
        (restore_service | trim | length == 0)
        or
        (restore_service.user is undefined)
        or
        (restore_service.user is none)
        or
        (restore_service.user | trim | length == 0)
        or
        (restore_service.pass is undefined)
        or
        (restore_service.pass is none)
        or
        (restore_service.pass | trim | length == 0)
      )
      else false }}"
