#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Sanity Check: System Checks"
  import_tasks: "sanity_check_system.yml"
  tags: always

- name: "Sanity Check: Tag Checks"
  import_tasks: "sanity_check_tags.yml"
  tags: always

- name: "Sanity Check: Backup Checks"
  import_tasks: "sanity_check_backup.yml"
  tags: always

- name: "Sanity Check: Logs Checks"
  import_tasks: "sanity_check_logs.yml"
  tags: always
