#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Set 'continuous_integration' variable
  set_fact:
    continuous_integration: "{{ continuous_integration | default(false,true) }}"

- name: Ensure TAGS are not being skipped
  assert:
    that:
      - '"{{ item }}" not in ansible_skip_tags'
    msg: "The tag you are trying to run is currently being skipped. Check your 'ansible.cfg' file."
  loop: "{{ ansible_run_tags }}"
  when:
   - not continuous_integration
   - "'homebox_' not in playbook_dir"
   - "'community' not in playbook_dir"

# Source: http://blog.leifmadsen.com/blog/2017/01/04/finding-available-ansible-tags-in-playbooks-and-roles/
- name: Get all available TAGS
  shell: |
    ansible-playbook homebox.yml --list-tags 2>&1 | grep "TASK TAGS" \
      | cut -d":" -f2 | awk '{sub(/\[/, "")sub(/\]/, "")}1' | sed -e 's/,//g' | xargs -n 1 | sort -u
  register: available_tags
  changed_when: no
  when:
   - not continuous_integration
   - "'homebox_mod' not in playbook_dir"
   - "'community' not in playbook_dir"

- name: Ensure TAGS are valid
  assert:
    that:
      - '"{{ item }}" in available_tags.stdout_lines'
    msg: "You must supply valid tag(s) via '--tags TAG' (get a list of valid tags by running 'sudo ansible-playbook homebox.yml --list-tags')"
  loop: "{{ ansible_run_tags }}"
  when:
   - not continuous_integration
   - "'homebox_' not in playbook_dir"
   - "'community' not in playbook_dir"
