#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Remove CPU Power | Check if 'cpupower.service' exists
  stat:
    path: "/etc/systemd/system/cpupower.service"
  register: cpupower_service

- name: Remove CPU Power | Stop and disable 'cpupower.service'
  systemd:
    name: cpupower
    state: stopped
    enabled: no
    daemon_reload: yes
  ignore_errors: yes
  when: cpupower_service.stat.exists

- name: Remove CPU Power | Delete 'cpupower.service'
  file:
    path: /etc/systemd/system/cpupower.service
    state: absent
  when: cpupower_service.stat.exists
