#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Stop and remove any existing container
  docker_container:
    name: tasmoadmin
    state: absent

- name: Create tasmoadmin directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/tasmoadmin
    - /opt/scripts/tasmoadmin

- name: Create and start container
  docker_container:
    name: tasmoadmin
    hostname: tasmoadmin
    image: "raymondmm/tasmoadmin"
    pull: yes
    published_ports:
      - "5555:80"
    env:
      USER_ID: "{{ uid }}"
      GROUP_ID: "{{ gid }}"
      TZ: "{{ timezone }}"
    labels:
      "com.github.homebox.homebox_managed": "true"
    volumes:
      - "/opt/tasmoadmin/data:/data:rw"
#      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - name: redbeard
        aliases:
          - tasmoadmin
    purge_networks: yes
    restart_policy: always
    state: started
