#########################################################################
# Title:         Homebox: UnionFS | UnionFS Tasks                      #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/homebox/homebox                   #
# --                                                                    #
#         Part of the Homebox project: https://homebox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "UnionFS | Create unionfs directories"
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }} recurse=yes"
  with_items:
    - /mnt/local/.unionfs-fuse

- name: "UnionFS | Install unionfs"
  apt:
    name: unionfs-fuse
    state: present

- name: "UnionFS | Import 'unionfs.service'"
  template:
    src: unionfs.service.j2
    dest: /etc/systemd/system/unionfs.service
    force: "{{ 'yes' if ('mounts_override' in ansible_run_tags) else 'no' }}"

- name: "UnionFS | Start 'unionfs.service'"
  systemd: name=unionfs state=started enabled=yes daemon_reload=yes
