##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Remote Mount Types
################################

- name: Variables | Set 'remote_mount_type' to 'plexdrive4'
  set_fact:
    remote_mount_type: "plexdrive4"
  when: (mounts.remote | lower == 'plexdrive4')
    or ((mounts.remote | lower == 'plexdrive') and ((ansible_memory_mb.real.total/1024)|round(0,'ceil')|int < 8))

- name: Variables | Set 'remote_mount_type' to 'plexdrive5'
  set_fact:
    remote_mount_type: "plexdrive5"
  when: (mounts.remote | lower == 'plexdrive5')
    or ((mounts.remote | lower == 'plexdrive') and ((ansible_memory_mb.real.total/1024)|round(0,'ceil')|int >= 8))

- name: Variables | Set 'remote_mount_type' to 'rclone_cache'
  set_fact:
    remote_mount_type: "rclone_cache"
  when: (mounts.remote | lower == 'rclone_cache')

- name: Variables | Set 'remote_mount_type' to 'rclone_vfs'
  set_fact:
    remote_mount_type: "rclone_vfs"
  when: (mounts.remote | lower == 'rclone_vfs')

- name: Variables | Fail when no valid remote mount type is specified.
  fail:
    msg: "'{{ mounts.remote }}' is not a valid remote mount type."
  when: remote_mount_type is undefined

################################
# Service Files List
################################

- name: Variables | Set 'service_files_list' variable
  set_fact:
    service_files_list:
      - "plexdrive4.service"
      - "plexdrive5.service"
      - "rclone_vfs.service"
      - "rclone_cache.service"
      - "rclone_vfs_primer.service"
      - "rclone_vfs_primer.timer"

- name: Variables | Set 'service_files_stat' variable
  stat:
    path: "/etc/systemd/system/{{ item }}"
  register: service_files_stat
  loop: "{{ service_files_list }}"

- name: Variables | Create empty 'service_files' list
  set_fact:
    service_files: []

- name: Variables | Build 'service_files' list
  set_fact:
    service_files: "{{ service_files + [ item.item ] }}"
  when: item.stat.exists
  loop: "{{ service_files_stat.results }}"
