#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Set User Variables
  import_tasks: "subtasks/user.yml"
  tags: always

- name: Clean Paths
  import_tasks: "subtasks/clean_paths.yml"
  tags: always

- name: Set Homebox Variables
  import_tasks: "subtasks/variables.yml"
  tags: always

- name: Set Homebox Role Variables
  import_tasks: "subtasks/role_variables.yml"
  tags: always

- name: APT Tasks
  import_tasks: "subtasks/apt.yml"
  tags: always

- name: "Set Homebox Type to 'homebox'"
  set_fact:
    homebox_type: "homebox"
  tags: homebox

- name: "Set Backup config settings"
  block:

  - name: "Decrypt | Check 'backup_config.yml' for encryption"
    shell: "head -1 {{ playbook_dir }}/backup_config.yml | grep -q \\$ANSIBLE_VAULT"
    register: encryption_check
    ignore_errors: yes
    changed_when: no
    failed_when: encryption_check.rc > 1
  
  - name: "Decrypt | Set 'file_is_encrypted' variable"
    set_fact:
      file_is_encrypted: "{{ ((encryption_check.rc == 0) | default(false,true)) }}"
  
  - name: "Decrypt | Decrypt 'backup_config.yml' when encrypted"
    shell: "ansible-vault decrypt {{ playbook_dir }}/backup_config.yml"
    become: yes
    become_user: "{{ homebox_yml.stat.pw_name }}"
    when: file_is_encrypted
  
  - name: "Set Homebox Type in backup_config"
    replace:
      path: "/home/{{ user.name }}/homebox/backup_config.yml"
      regexp: 'Homebox'
      replace: "{{ homebox_type }}"
  
  - name: "Set rclone remote in backup_config"
    replace:
      path: "/home/{{ user.name }}/homebox/backup_config.yml"
      regexp: 'rclone.remote'
      replace: "{{ rclone.remote }}"
  
  - name: "Re-encrypt | Re-encrypt 'backup_config.yml' if previously encrypted"
    shell: "ansible-vault encrypt {{ playbook_dir }}/backup_config.yml"
    become: yes
    become_user: "{{ homebox_yml.stat.pw_name }}"
    when: file_is_encrypted

  tags:
    - homebox
