#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Stop and remove any existing container
  docker_container:
    name: nodered
    state: absent

- name: Create nodered directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/nodered
    - /opt/scripts/nodered

- name: Create and start container
  docker_container:
    hostname: nodered
    name: nodered
    image: "nodered/node-red:latest"
    pull: yes
    published_ports:
      - "1880:1880"
    env:
      USER_ID: "{{ uid }}"
      GROUP_ID: "{{ gid }}"
      TZ: "{{ timezone }}"
    labels:
      "com.github.homebox.homebox_managed": "true"
    volumes:
      - "/opt/nodered:/data:rw"
#      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - name: local
        aliases:
          - nodered
    purge_networks: yes
    restart_policy: always
    state: started

- name: Stop container to customize network
  docker_container:
    name: nodered
    state: stopped

- name: "Remove from local network to set static ip"
  shell: "docker network disconnect local nodered"
  ignore_errors: yes

- name: "Connect to local network on static ip"
  shell: "docker network connect local nodered --ip 172.18.0.4"

- name: Start container to apply network changes
  docker_container:
    name: nodered
    state: started
