#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare-dns
  vars:
    subdomain: nodered

- name: Slurp hashed htpasswd
  slurp:
    src: "/opt/traefik/.htpasswd"
  register: hashed

- name: Set hashed password
  set_fact:
    htpasswd: "{{ hashed['content'] | b64decode }}"

- name: Stop and remove any existing container
  docker_container:
    name: nodered
    state: absent

- name: Create nodered directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/nodered
    - /opt/scripts/nodered

- name: Create and start container
  docker_container:
    name: nodered
    image: "nodered/node-red:latest"
    pull: yes
    published_ports:
      - "1880:1880"
    env:
      USER_ID: "{{ uid }}"
      GROUP_ID: "{{ gid }}"
    labels:
      traefik.enable: "{{ traefik.enable }}"
      traefik.backend: "nodered"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:nodered.{{ user.domain }}"
      traefik.port: "1880"
      traefik.frontend.auth.basic: "{{ htpasswd }}"
      traefik.docker.network: "redbeard"
      "com.github.homebox.homebox_managed": "true"
    volumes:
      - "/opt/nodered:/data:rw"
    networks:
      - name: redbeard
        aliases:
          - nodered
    purge_networks: yes
    restart_policy: always
    state: started
