#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Start 'unionfs.service'
  systemd: name=unionfs state=started enabled=yes daemon_reload=yes
  when: (unionfs_service.stat.exists) and (unionfs_service_running)

- name: Start 'mergerfs.service'
  systemd: name=mergerfs state=started enabled=yes daemon_reload=yes
  when: (mergerfs_service.stat.exists) and (mergerfs_service_running)

- name: Wait for 30 seconds before commencing
  wait_for:
    timeout: 30
  when: (docker_binary.stat.exists) and (docker_service_running) and (docker_running_containers.stdout | trim | length > 0)

- name: "Re-start all previously running Docker containers"
  shell: 'docker start {{ docker_running_containers.stdout }}'
  ignore_errors: yes
  when: (docker_binary.stat.exists) and (docker_service_running) and (docker_running_containers.stdout | trim | length > 0)
