#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare-dns
  vars:
    subdomain: mosquitto

#- name: Slurp hashed htpasswd
#  slurp:
#    src: "/opt/traefik/.htpasswd"
#  register: hashed
#
#- name: Set hashed password
#  set_fact:
#    htpasswd: "{{ hashed['content'] | b64decode }}"

- name: Stop and remove any existing container
  docker_container:
    name: mosquitto
    state: absent

- name: Create mosquitto directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/mosquitto
    - /opt/scripts/mosquitto

- name: Create and start container
  docker_container:
    name: mosquitto
    image: "eclipse-mosquitto"
    pull: yes
    published_ports:
      - 1883:1883
      - 8883:8883
      - 9001:9001
    env:
      USER_ID: "{{ uid }}"
      GROUP_ID: "{{ gid }}"
      TZ: "{{ tz }}"
    labels:
      traefik.enable: "false"
      traefik.backend: "mosquitto"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:mosquitto.{{ user.domain }}"
      traefik.port: "1883"
      traefik.frontend.auth.basic: "{{ htpasswd }}"
      traefik.docker.network: "redbeard"
      "com.github.homebox.homebox_managed": "true"
    volumes:
      - "/opt/mosquitto/config:/mosquitto/config:rw"
      - "/opt/mosquitto/data:/mosquitto/data:rw"
      - "/opt/mosquitto/logs:/mosquitto/logs:rw"
    networks:
      - name: redbeard
        aliases:
          - mosquitto
    purge_networks: yes
    restart_policy: always
    state: started
