#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: BTRFS Tasks
  include_tasks: "btrfs.yml"
  loop:
    - /opt
    - /mnt/local
  loop_control:
    loop_var: outer_item

- name: Create common directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /home/{{ user.name }}
    - /home/{{ user.name }}/logs
    - /home/{{ user.name }}/.config
    - /home/{{ user.name }}/.config/pip
    - /opt
    - /mnt/local

- name: Install required packages
  apt:
    state: present
    name:
      - apt-transport-https
      - ca-certificates
      - software-properties-common

#- name: Add Ubuntu repositories
#  apt_repository:
#    repo: "{{ item }}"
#    state: present
#    update_cache: yes
#  with_items:
#    - 'deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} multiverse'
#    - 'deb-src http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} multiverse'
#    - 'deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }}-updates multiverse'
#    - 'deb-src http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }}-updates multiverse'
#  when: ansible_distribution == 'Ubuntu'
#
#- name: Add Debian repositories
#  apt_repository:
#    repo: "{{ item }}"
#    state: present
#    update_cache: yes
#  with_items:
#    - deb https://deb.debian.org/debian {{ ansible_distribution_release }} main contrib non-free
#    - deb-src https://deb.debian.org/debian {{ ansible_distribution_release }} main contrib non-free
#    - deb https://deb.debian.org/debian-security/ {{ ansible_distribution_release }}/updates main contrib non-free
#    - deb-src https://deb.debian.org/debian-security/ {{ ansible_distribution_release }}/updates main contrib non-free
#    - deb https://deb.debian.org/debian {{ ansible_distribution_release }}-updates main contrib non-free
#    - deb-src https://deb.debian.org/debian {{ ansible_distribution_release }}-updates main contrib non-free
#    - deb https://deb.debian.org/debian {{ ansible_distribution_release }}-backports main contrib non-free
#    - deb-src https://deb.debian.org/debian {{ ansible_distribution_release }}-backports main contrib non-free
#  when: ansible_distribution == 'Debian'

- name: Install common packages
  apt:
    state: present
    name:
      - "nano"
      - "zip"
      - "unzip"
      - "p7zip"
      - "curl"
      - "httpie"
      - "sqlite3"
      - "tree"
      - "lsof"
      - "man-db"
      - "ksmtuned"
      - "git"
      - "pwgen"
      - "logrotate"
      - "htop"
      - "iotop"
      - "nload"
      - "fail2ban"
      - "ufw"
      - "ncdu"
      - "mc"
      - "speedtest-cli"
      - "dnsutils"
      - "screen"
      - "tmux"
      - "apache2-utils"
      - "jq"
#      - "lib32z1"
      - "moreutils"
  ignore_errors: yes

- name: Install extra packages
  apt:
    state: present
    name:
      - "run-one"
  ignore_errors: yes

- name: Install unrar
  apt:
    name: unrar
    state: present
  ignore_errors: yes

- name: Check to see if unrar installed
  stat:
    path: "/usr/bin/unrar"
  register: unrar_binary

- name: Install unrar-free if unrar was not installed
  apt:
    name: unrar-free
    state: present
  ignore_errors: yes
  when: (not unrar_binary.stat.exists)

- name: "Import pip.conf into /home/{{ user.name }}/.config/pip/pip.conf"
  copy:
    src: "pip.conf"
    dest: "/home/{{ user.name }}/.config/pip/pip.conf"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0775
    force: yes

- name: Install common pip modules
  pip:
    state: present
    name:
      - passlib
      - ansible-toolbox
      - ndg-httpsclient
      - dnspython
      - yq
      - lxml
      - apprise
      - jmespath
  ignore_errors: yes

- name: Install nodejs
  import_role:
    name: nodejs
  tags: nodejs
  ignore_errors: yes

- name: Install hostess
  import_role:
    name: hostess
  tags: hostess
  ignore_errors: yes

- name: Install ngrok
  import_role:
    name: ngrok
  tags: ngrok
  ignore_errors: yes

- name: Install iperf3
  import_role:
    name: iperf3
  tags: iperf3
  ignore_errors: yes

- name: Install nethogs
  import_role:
    name: nethogs
  tags: nethogs
  ignore_errors: yes
