#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Handers | Update 'locales'
  command: dpkg-reconfigure --frontend noninteractive locales

- name: Handers | Update 'tzdata'
  command: dpkg-reconfigure --frontend noninteractive tzdata
