##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Continuous Integration
################################

continuous_integration: false
