#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Stop and remove any existing container
  docker_container:
    name: homeassistant
    state: absent

- name: Create homeassistant directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/homeassistant
    - /opt/homeassistant/ssl
    - /opt/scripts/homeassistant

- name: Create and start container
  docker_container:
    name: homeassistant
    hostname: homeassistant
    image: "homeassistant/raspberrypi4-64-homeassistant"
    pull: yes
#    network_mode: host # Unsure why host mode was used testing to find out
    published_ports:
      - "8123:8123"
    env:
      USER_ID: "{{ uid }}"
      GROUP_ID: "{{ gid }}"
      TZ: "{{ timezone }}"
    labels:
      "com.github.homebox.homebox_managed": "true"
    volumes:
      - "/opt/homeassistant:/config:rw"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - name: local
        aliases:
          - homeassistant
    purge_networks: yes
    restart_policy: always
    state: started

- name: Stop container to customize network
  docker_container:
    name: homeassistant
    state: stopped

- name: "Remove from local network to set static ip"
  shell: "docker network disconnect local homeassistant"
  ignore_errors: yes

- name: "Connect to local network on static ip"
  shell: "docker network connect local homeassistant --ip 172.18.0.7"

- name: Start container to apply network changes
  docker_container:
    name: homeassistant
    state: started