#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Settings | Copy"
  include_tasks: "subtasks/copy.yml"
  vars:
    file: "{{ outer_item }}"

- name: "Settings | Decrypt"
  include_tasks: "subtasks/decrypt.yml"
  vars:
    file: "{{ outer_item }}"
  when: (outer_item != "ansible.cfg")

- name: "Settings | Updater"
  include_tasks: "subtasks/updater.yml"
  vars:
    file: "{{ outer_item }}"
  when: (outer_item != "ansible.cfg")

- name: "Settings | Re-encrypt"
  include_tasks: "subtasks/reencrypt.yml"
  vars:
    file: "{{ outer_item }}"
  when: (outer_item != "ansible.cfg")
