#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Stop and remove any existing container
  docker_container:
    name: pihole
    state: absent

- name: Create pihole directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/pihole
    - /opt/scripts/pihole

- name: Create and start container
  docker_container:
    name: pihole
    hostname: pihole
    image: "pihole/pihole:latest"
    pull: no
    capabilities:
      - NET_ADMIN
    network_mode: host
#    published_ports:
#      - "53:53/tcp"
#      - "53:53/udp"
#      - "67:67/udp"
#      - "8080:80"
#      - "8443:443"
    env:
      USER_ID: "{{ uid }}"
      GROUP_ID: "{{ gid }}"
      WEBPASSWORD: "{{ user.pass }}"
      TZ: "{{ timezone }}"
    labels:
      "com.github.homebox.homebox_managed": "true"
    volumes:
      - "/opt/pihole/etc-pihole/:/etc/pihole/"
      - "/opt/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/"
#      - "/etc/localtime:/etc/localtime:ro"
#    networks:
#      - name: redbeard
#        aliases:
#          - pihole
    purge_networks: yes
    restart_policy: always
    state: started
